name: dockerhub build and push
on:
    workflow_dispatch:
    push:
      branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@main
      
      - name: Set variables
        id: set_var
        run: |
          content=`cat ./config.json`
          version=`echo $(jq -r '.version' <<< "$content")`
          echo "version=${version}" >> $GITHUB_OUTPUT
          REPO_NAME=$(echo ${{ github.repository }})
          repo_name=`basename ${{ github.repository }}`
          echo "repo_name=${repo_name}" >> $GITHUB_OUTPUT
          DOCKER_IMAGE="${{ secrets.DOCKER_USER }}/${repo_name}"
          echo "docker_image=${DOCKER_IMAGE}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and deploy master image to dockerhub
        working-directory: .
        env:
          GITHUB_SHA: ${{ github.sha}}
          GITHUB_REF: ${{ github.ref}}
        run: |
          ref="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
          docker buildx build --push \
              --build-arg CI=github --build-arg BUILD_VERSION=${{steps.set_var.outputs.version}} --build-arg GITHUB_SHA=${GITHUB_SHA} --build-arg GIT_BRANCH=${ref} \
              --platform linux/arm64 \
              -t ${{steps.set_var.outputs.docker_image}}:${{steps.set_var.outputs.version}} -t ${{steps.set_var.outputs.docker_image}}:latest .

      # - name: Checkout photo_to_kodak_frame_bot-homeassistant config.json
      #   uses: actions/checkout@master
      #   with: 
      #     repository: ad/photo_to_kodak_frame_bot-homeassistant
      #     token: ${{ secrets.TELEGRAM_DOORKEEPER_HOMEASSISTANT_TOKEN }}
      #     path: ./photo_to_kodak_frame_bot-homeassistant

      # - name: Update file and push updated file
      #   run: |
      #     cd ./photo_to_kodak_frame_bot-homeassistant
      #     sed -i'' -E 's/"version": *"[^"]*"/"version": "'${{steps.set_var.outputs.version}}'"/g' config.json
      #     cat config.json
      #     git add config.json
      #     git config user.name github-actions
      #     git config user.email github-actions@github.com
      #     git commit -am "Update version in config.json"
      #     git push